version: '3.2'

# networks:
#     app-network:
#         driver: bridge

services:

    db:
        image: mysql:latest
        container_name: mysql8
        ports:
          - 890:3306
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - TZ=Asia/Taipei
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        # networks:
        #   - app-network

    develop:
        build:
            context: .
            dockerfile: pdo.dockerfile
        container_name: develop
        working_dir: /var/www/html
        volumes:
            - ./autoload_test/:/var/www/html
            - ./php/php.ini:/etc/php/7.2/apache2
        ports:
            - 801:80
        # networks:
        #   - app-network